// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqtx_UKmwU8torVgzBJ1kwnL-vgp2NcM',
    appId: '1:840249200728:web:a5464c81fc6550b9903a2d',
    messagingSenderId: '840249200728',
    projectId: 'easy-conect',
    authDomain: 'easy-conect.firebaseapp.com',
    storageBucket: 'easy-conect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8rdeeMLQFrkKilcsCjKKGlGwVLcW0Cy0',
    appId: '1:840249200728:android:57c25aa9f7dbbcd1903a2d',
    messagingSenderId: '840249200728',
    projectId: 'easy-conect',
    storageBucket: 'easy-conect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWJbDvdRs8W0uiJElKHXZpX2NCXqJs2c',
    appId: '1:840249200728:ios:8bf9824c0d22fee0903a2d',
    messagingSenderId: '840249200728',
    projectId: 'easy-conect',
    storageBucket: 'easy-conect.firebasestorage.app',
    iosBundleId: 'com.example.easyConect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWJbDvdRs8W0uiJElKHXZpX2NCXqJs2c',
    appId: '1:840249200728:ios:8bf9824c0d22fee0903a2d',
    messagingSenderId: '840249200728',
    projectId: 'easy-conect',
    storageBucket: 'easy-conect.firebasestorage.app',
    iosBundleId: 'com.example.easyConect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqtx_UKmwU8torVgzBJ1kwnL-vgp2NcM',
    appId: '1:840249200728:web:f0c0ad0a7e1eb0cc903a2d',
    messagingSenderId: '840249200728',
    projectId: 'easy-conect',
    authDomain: 'easy-conect.firebaseapp.com',
    storageBucket: 'easy-conect.firebasestorage.app',
  );
}
